config/routes.rb
# -*- encoding : utf-8 -*-
Smartbooks::Application.routes.draw do
  resources :event_lines
  resources :fiscal_years do
    resources :events
    resources :accounts do
      resources :preliminary_events
    end
    resources :vat_reports
    resource :income_statement
    resource :balance_sheet
  end

  match '/' => 'fiscal_years#index'
end

app/controllers/vat_reports_controller.rb
# -*- encoding : utf-8 -*-
class VatReportsController < ApplicationController
  def new
    @fiscal_year = FiscalYear.find(params[:fiscal_year_id])
    if params[:month]
      @debt = @fiscal_year.vat_debt
      @receivables = @fiscal_year.vat_receivables
    end
  end
end

app/helpers/vat_reports_helper.rb
# -*- encoding : utf-8 -*-
module VatReportsHelper
end

app/views/vat_reports/new.html.erb
<h1>
  Arvonlisäverolaskelma
</h1>

<p>
  <%= form_tag(new_fiscal_year_vat_report_path(@fiscal_year),
              :method => :get) do %>
    <%= month_select_tag(params[:month]) %>
    <%= submit_tag "Valitse" %>
  <% end %>
</p>

<% if params[:month] %>
  
  <table>
    <tr>
      <th>Vero myynnistä</th>
    </tr>
    
    <tr>
      <td>Arvonlisäverovelka 22%</td>
      <td>
        <%= @debt.formatted_total(:month => params[:month]) %>
      </td>
    </tr>
    
    <tr>
      <th>Vähennettävät verot</th>
    </tr>
    
    <tr>
      <td>Arvonlisäverosaamiset</td>
      <td>
        <%= @receivables.formatted_total(:month => params[:month]) %>
      </td>
    </tr>
    
    <tr>
      <td>Edellisten kausien vähentämättä jääneet verot</td>
      <td>
        <% if params[:month].to_i == 1 %>
          0
        <% else %>
          <%= @receivables.formatted_total(:month => 1..(params[:month].to_i - 1)) %>
        <% end %>
      </td>
    </tr>
    
    <tr>
      <th>Maksettava vero</th>
      <th>
        <%= @fiscal_year.payable_vat_for(params[:month]) %>
      </th>
    </tr>
    
    <tr>
      <th>Seuraaville kausille siirtyvät vähennykset</th>
      <th>
        <%= @fiscal_year.transferred_vat_receivables_for(params[:month]) %>
      </th>
    </tr>
  </table>
  
<% end %>