config/routes.rb
# -*- encoding : utf-8 -*-
Smartbooks::Application.routes.draw do
  resources :event_lines
  resources :fiscal_years do
    resources :events
    resources :accounts do
      resources :preliminary_events
    end
    resources :vat_reports
    resource :income_statement
    resource :balance_sheet
  end

  match '/' => 'fiscal_years#index'
end

app/models/event.rb
# -*- encoding : utf-8 -*-
class Event < ActiveRecord::Base
  before_create :set_receipt_number
  mount_uploader :receipt, ReceiptUploader

  has_many    :event_lines, :dependent => :delete_all
  belongs_to  :fiscal_year
  accepts_nested_attributes_for :event_lines
  has_one :preliminary_event, :inverse_of => :event

  validates_presence_of :event_date
  before_validation :validate_event_line_sum

  def validate_event_line_sum
    unless event_lines.map(&:amount).sum == 0
      errors.add :event_lines, "must add up to zero"
    end
  end

  def self.parse_events(fiscal_year, arr)
    arr.each do |event|
      self.parse_event(fiscal_year, event)
    end
  end

  def self.parse_event(fiscal_year, event)
    logger.debug("EVENT SEXP: #{event.inspect}")
    @event = fiscal_year.events.build(:receipt_number => event[1],
                                :event_date => event[2][1..-1].map(&:to_i).join("-"),
                                :description => event[3])

    @event_lines = event[4]
    logger.debug("EVENT LINES SEXP: #{@event_lines.inspect}")
    @event_lines.each do |el|
      @account = Account.find_by_account_number(el.first)
      @event.event_lines.build(:account_id => @account.id,
                                 :amount => el.last.last.to_s.to_i)
    end

    logger.debug("EVENT DATE: <#{@event.event_date.inspect}>")
    @event.save!
    @event
  end

  def self.next_receipt_number
    (maximum('receipt_number').to_i + 1) || 1
  end

  def update_lines!(lines)
    transaction do
      event_lines.delete_all
      lines = lines.respond_to?(:values) ? lines.values : lines
      lines.each do |line|
        line.stringify_keys!
        next if %w(credit debit amount).all? { |i| line[i].blank? }
        event_lines.build(line)
      end
      save!
    end
  end

  def preliminary_event_id=(id)
    self.preliminary_event = fiscal_year.preliminary_events.where(:id => id).first
  end

  def preliminary_event_id
    (p = preliminary_event) ? p.id : nil
  end

  private

    def set_receipt_number
      self.receipt_number = Event.next_receipt_number if receipt_number.blank?
    end
end

app/controllers/events_controller.rb
# -*- encoding : utf-8 -*-
require 'digest/sha1'
class EventsController < ApplicationController
  before_filter :get_fiscal_year



  # GET /events
  # GET /events.xml
  def index
    @events = @fiscal_year.ordered_events(params[:start_date], params[:end_date])
      #if params[:start_date]
      #start = Date.parse(params[:start_date])
      #@events = @events.where(["event_date >= ?", start.to_s(:db)])
    #end

    #if params[:end_date]
      #end_date = Date.parse(params[:end_date])
      #@events = @events.where(["event_date <= ?", end_date.to_s(:db)])
    #end
  end

  # GET /events/new
  def new
    @event = Event.new
    @accounts = @fiscal_year.accounts.find_for_dropdown
    @lines = []
    fetch_preliminary_data

    6.times { @lines << EventLine.new }
  end

  # GET /events/1;edit
  def edit
    @event = @fiscal_year.events.find(params[:id])
    @accounts = @fiscal_year.accounts.find_for_dropdown
    @lines = []
    @lines += @event.event_lines
    2.times { @lines << EventLine.new }
  end

  # POST /events
  # POST /events.xml
  def create
    #@event = @fiscal_year.create_event(params[:event], params[:line])
    @event = @fiscal_year.build_event(cleaned_up_event_params(params[:event]))
    @event.save!
    flash[:notice] = 'Event was successfully created.'
    redirect_to after_create_url

  rescue ActiveRecord::RecordInvalid
    flash[:warning] = 'Saving event failed.'
    @lines = @event.event_lines
    2.times { @lines << EventLine.new }
    @accounts = @fiscal_year.accounts.find_for_dropdown

    render :action => "new"
  end

  def update
    @event = @fiscal_year.events.find(params[:id])
    @event.update_attributes!(cleaned_up_event_params(params[:event]))
    #@event.update_lines!(params[:line])
    flash[:notice] = 'Event was successfully updated.'
    redirect_to fiscal_year_events_url(:fiscal_year_id => @fiscal_year,
                            :anchor => "event_#{@event.to_param}")
    rescue ActiveRecord::RecordInvalid
      flash[:warning] = 'Saving event failed.'
      @lines = @event.event_lines
      2.times { @lines << EventLine.new }
      @accounts = Account.find_for_dropdown

      render :action => "edit"
  end

  private

    def cleaned_up_event_params(params)
      params[:event_lines_attributes].reject!{|k,v| (v[:debit].blank? && v[:credit].blank?) || v[:debit] == v[:credit] }
      params
    end

    def fetch_preliminary_data
      if params[:preliminary_event_id].present?
        @preliminary_event = @fiscal_year.preliminary_events.where(:id => params[:preliminary_event_id]).first

        if @preliminary_event
          @event.description = "#{@preliminary_event.description} (#{[@preliminary_event.counterpart, @preliminary_event.message].reject(&:blank?).join(", ")})"
          @event.event_date = @preliminary_event.booking_date
          @event.receipt_number = @preliminary_event.reference
          @lines << EventLine.new do |el|
            el.account = @preliminary_event.account
            el.amount = @preliminary_event.amount_cents
          end
        end
      end
    end

    def after_create_url
      if @pe = @event.preliminary_event
        fiscal_year_account_preliminary_events_path(@fiscal_year, @pe.account)
      else
        fiscal_year_events_url(:fiscal_year_id => @fiscal_year,
                               :anchor => "event_#{@event.to_param}")
      end
    end
end

app/helpers/events_helper.rb
# -*- encoding : utf-8 -*-
module EventsHelper
end

app/views/events/_form.html.erb
<% content_for :javascript do %>
  <%= javascript_include_tag 'events/new', 'effects', 'controls',
                    "/fiscal_years/#{@fiscal_year.id}/accounts" %>
<% end %>

<% if @event.errors.any? %>
  <ul>
    <% @event.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>

<%= form_for([@fiscal_year, @event], :html => {:id => "event_form"}) do |f| %>
<div class="row">
  <div class="small-12 columns">
    <p>
      <label for="event_description">Description:</label> <%= f.text_field(:description, :size => 40) %>
    </p>

    <p>
      <label for="event_receipt_number">Receipt Number:</label> <%= f.text_field(:receipt_number, :size => 4) %>
    </p>

    <p>
      <label for="event_event_date">Date:</label> <%= f.text_field :event_date, :size => 12, :class => "date" %>
    </p>

    <p><a class="button" id="vat-24">VAT 24%</a>
      <a class="button" id="vat-24-10">10 yks.ott., VAT 24%</a>
    </p>
  </div>
</div>

  <ul class="event_lines" id="event_lines">
    <li class="row">
      <h4>
        <span class="small-2 columns small-offset-6">
          Debit
        </span>
        <span class="small-3 columns end">
          Credit
        </span>
      </h4>
    </li>

    <% @lines.each_with_index do |line, idx| %>
      <% line.id = idx + 1 if line.id.blank? %>
      <li class="row event_line">
      <%= f.fields_for(:event_lines, line) do |f2| %>
        <div class="account small-6 columns">
          <%= f2.select(:account_id, @accounts.map{|a| [a.title, a.id]}, :include_blank => true) %>
        </div>
        <div class="debit small-2 columns">
          <%= f2.text_field :debit, :size => 8, :value => trimmed(line.debit) %>
        </div>
        <div class="credit small-3 end columns">
          <div class="row collapse">
            <div class="small-8 columns">
              <%= f2.text_field :credit, :size => 8, :value => trimmed(line.credit) %>
            </div>
            <div class="small-4 columns">
              <a href="#" class="split-vat-button postfix button">Split VAT</a>
            </div>
          </div>
        </div>
      <% end %>
      </li>
    <% end %>
  </ul>

  <p>
    <label for="event_receipt">Receipt:</label>
    <% if @event.receipt? %>
      <%= link_to @event.receipt.file.filename, @event.receipt_url %><br>
    <% end %>
    <%= f.file_field :receipt %>
  </p>

  <p>
    <% if @preliminary_event %>
      <%= f.hidden_field :preliminary_event_id, :value => @preliminary_event.id %>
    <% end %>
    <%= submit_tag @event.new_record? ? "Create" : "Save" %>
  </p>
<% end %>

app/views/events/edit.html.erb
<% @page_title = "Edit event #{@event.description}" %>

<h1>Edit Event</h1>

<%= render :partial => "form" %>

<%= link_to 'Back', fiscal_year_events_path(@fiscal_year) %>

app/views/events/index.html.erb
<% @page_title = "Events for #{@fiscal_year.description}" %>
<%= content_for :javascript do %>
  <%= javascript_include_tag 'date_selector', 'fiscal_years/index' %>
<% end %>
<h1>Listing events</h1>

<ul>
  <li>
    <%= link_to "Balance Sheet", fiscal_year_balance_sheet_path(@fiscal_year) %>
  </li>

  <li>
    <%= link_to "Income Statement", fiscal_year_income_statement_path(@fiscal_year) %>
  </li>

</ul>

<p>
  <%= link_to "Add new event", new_fiscal_year_event_path(@fiscal_year), :accesskey => "n" %>
</p>

<%= form_tag(fiscal_year_events_path(@fiscal_year), :method => 'get') do %>
<p>
  Limit the time frame: <%= text_field_tag "start_date", params[:start_date], :class => 'date' %> to <%= text_field_tag "end_date", params[:end_date], :class => 'date' %>
  <%= submit_tag "Limit" %>
</p>
<% end %>

<ul id="events">
<% for event in @events %>

  <li id="event_<%= event.id %>">
    <h4>
      <span class="event_date"><%= event.event_date.to_s %></span>
      <span class="event_id"><%= event.receipt_number %></span>
      <span class="description">
        <%=h event.description %>
      </span>

      <%= link_to "Edit", [:edit, @fiscal_year, event], :class => "edit_event_link" %>
    </h4>

    <ul class="event_lines">
      <% for event_line in event.event_lines %>
      <li>
        <span class="event_line_account">
          <%= link_to event_line.account.title,
                      fiscal_year_account_path(@fiscal_year, event_line.account) %>
        </span>
        <%= colored_sum(event_line.sum) %>
      </li>
      <% end %>
    </ul>
  </li>

<% end %>
</ul>

<p>
  <%= link_to "Add new event", new_fiscal_year_event_path(@fiscal_year) %>
</p>

app/views/events/new.html.erb
<% content_for :javascript do %>
  <%= javascript_include_tag 'events/new', 'effects', 'controls',
                    "/fiscal_years/#{@fiscal_year.id}/accounts" %>
<% end %>

<h1>New event</h1>

<%= error_messages_for :event %>

<% form_for(:event, :url => fiscal_year_events_path(@fiscal_year), :html => {:id => "event_form"}) do |f| %>

<div>
  <%= hidden_field_tag "form_token", @form_token %>
</div>

  <p>
    <label for="event_description">Description:</label> <%= f.text_field(:description, :size => 40) %>
  </p>
  
  <p>
    <label for="event_receipt_number">Receipt Number:</label> <%= f.text_field(:receipt_number, :size => 4) %>
  </p>
  
  <p>
    <label for="event_event_date">Date:</label> <%= f.text_field :event_date, :size => 12, :class => "date" %>
  </p>

  <ul class="event_lines">
    <li>
      <h4>
        <span class="debit">
          Debit
        </span>
        <span class="credit">
          Credit
        </span>
      </h4>
    </li>
    
    <% @lines.each_with_index do |@line, idx| %>
      <% @line.id = idx + 1 if @line.id.blank? %>
      <li>
        <span class="account">
          <%= select( "line[]", :account_id, @accounts.map{|a| [a.title, a.id]}, :include_blank => true) %>
        </span>
        <span class="debit">
          <%= text_field "line[]", :debit, :size => 8, :value => trimmed(@line.debit) %>
        </span>
        <span class="credit">
          <%= text_field "line[]", :credit, :size => 8, :value => trimmed(@line.credit) %>
        </span>
      </li>
    <% end %>
  </ul>

  <p>
    <%= submit_tag "Create" %>
  </p>
<% end %>

<%= link_to 'Back', fiscal_year_events_path(@fiscal_year) %>